import { ShoppingBag, Car, Sun, Activity, Building } from "lucide-react";

export const DEMO_PRESETS = [
  {
    id: "varejo_retail",
    niche: "Varejo",
    name: "Varejo & Loja",
    description: "Foco em PDV, controle de estoque, compras de fornecedores e recompra de clientes, com financeiro integrado.",
    icon: ShoppingBag,
    color: "#F59E0B",
    bgAccent: "bg-amber-500/10 border-amber-500/20 text-amber-400",
    modules: {
      crm: true,
      educacao: false,
      clinica: false,
      financeiro: true,
      marketing: true,
      engajamento: true,
      rh: true,
      bi: true,
    },
    stages: [
      { id: '1', name: "Novo Contato / Pedido", color: "#06B6D4", textClass: "text-[#06B6D4]", bgClass: "bg-[#06B6D4]/10", borderClass: "border-[#06B6D4]/20", type: 'comercial' },
      { id: '2', name: "Orçamento / Carrinho", color: "#6366F1", textClass: "text-indigo-400", bgClass: "bg-indigo-500/10", borderClass: "border-indigo-500/20", type: 'comercial' },
      { id: '3', name: "Negociação & Pagamento", color: "#8B5CF6", textClass: "text-[#8B5CF6]", bgClass: "bg-[#8B5CF6]/10", borderClass: "border-[#8B5CF6]/20", type: 'comercial' },
      { id: '4', name: "Separação & Entrega", color: "#F59E0B", textClass: "text-amber-400", bgClass: "bg-amber-500/10", borderClass: "border-amber-500/20", type: 'comercial' },
      { id: '5', name: "Venda Concluída / Pós-venda", color: "#10B981", textClass: "text-emerald-400", bgClass: "bg-emerald-500/10", borderClass: "border-emerald-500/20", type: 'comercial' },
    ],
  },
  {
    id: "solar_corp",
    niche: "Solar",
    name: "Energia Solar & Engenharia",
    description: "Ideal para integradores de energia fotovoltaica, focado em levantamento elétrico, projetos técnicos complexos de homologação com concessionárias.",
    icon: Sun,
    color: "#F59E0B",
    bgAccent: "bg-amber-500/10 border-amber-500/20 text-amber-400",
    modules: {
      crm: true,
      educacao: false,
      clinica: false,
      financeiro: true,
      marketing: false,
      engajamento: true,
      rh: true,
      bi: true,
    },
    stages: [
      { id: '1', name: "Conta de Luz / Contato", color: "#06B6D4", textClass: "text-[#06B6D4]", bgClass: "bg-[#06B6D4]/10", borderClass: "border-[#06B6D4]/20", type: 'comercial' },
      { id: '2', name: "Estudo de Viabilidade", color: "#6366F1", textClass: "text-indigo-400", bgClass: "bg-indigo-500/10", borderClass: "border-indigo-500/20", type: 'comercial' },
      { id: '3', name: "Negociação Bancária / Fin", color: "#8B5CF6", textClass: "text-[#8B5CF6]", bgClass: "bg-[#8B5CF6]/10", borderClass: "border-[#8B5CF6]/20", type: 'comercial' },
      { id: '4', name: "Homologação Concessionária", color: "#F59E0B", textClass: "text-amber-400", bgClass: "bg-amber-500/10", borderClass: "border-amber-500/20", type: 'comercial' },
      { id: '5', name: "Instalado & Operando", color: "#10B981", textClass: "text-emerald-400", bgClass: "bg-emerald-500/10", borderClass: "border-emerald-500/20", type: 'comercial' },
    ],
  },
  {
    id: "aesthetic_clinic",
    niche: "Clínica",
    name: "Clínica de Estética & Dermatologia",
    description: "Combina funil de vendas cosméticas com prontuários médicos EHR completos, telemedicina para retornos, agenda de múltiplos médicos e faturamento integrado.",
    icon: Activity,
    color: "#E11D48",
    bgAccent: "bg-rose-500/10 border-rose-500/20 text-rose-400",
    modules: {
      crm: true,
      educacao: false,
      clinica: true,
      financeiro: true,
      marketing: true,
      engajamento: true,
      rh: true,
      bi: true,
    },
    stages: [
      { id: '1', name: "Visualização / Agendamento", color: "#EC4899", textClass: "text-pink-400", bgClass: "bg-pink-500/10", borderClass: "border-pink-500/20", type: 'comercial' },
      { id: '2', name: "Primeira Avaliação Médica", color: "#6366F1", textClass: "text-indigo-400", bgClass: "bg-indigo-500/10", borderClass: "border-indigo-500/25", type: 'comercial' },
      { id: '3', name: "Protocolo Indicado / Orçamento", color: "#8B5CF6", textClass: "text-[#8B5CF6]", bgClass: "bg-[#8B5CF6]/10", borderClass: "border-[#8B5CF6]/20", type: 'comercial' },
      { id: '4', name: "Fechamento de Pacote / Injet", color: "#F59E0B", textClass: "text-amber-400", bgClass: "bg-amber-500/10", borderClass: "border-amber-500/20", type: 'comercial' },
      { id: '5', name: "Fase de Aplicação & Botox Ativo", color: "#10B981", textClass: "text-emerald-400", bgClass: "bg-emerald-500/10", borderClass: "border-emerald-500/20", type: 'comercial' },
    ],
  },
  {
    id: "real_estate",
    niche: "Imobiliária",
    name: "Imobiliária Agency & Builders",
    description: "Configurado para venda de habitação premium e locação, controle de agendamento de visitas com corretores e análise rigorosa de crédito integrados à proposta.",
    icon: Building,
    color: "#2563EB",
    bgAccent: "bg-blue-500/10 border-blue-500/20 text-blue-400",
    modules: {
      crm: true,
      educacao: false,
      clinica: false,
      financeiro: true,
      marketing: true,
      engajamento: true,
      rh: true,
      bi: true,
    },
    stages: [
      { id: '1', name: "Novo Contato / Portal", color: "#06B6D4", textClass: "text-[#06B6D4]", bgClass: "bg-[#06B6D4]/10", borderClass: "border-[#06B6D4]/20", type: 'comercial' },
      { id: '2', name: "Visita Agendada", color: "#6366F1", textClass: "text-indigo-400", bgClass: "bg-indigo-500/10", borderClass: "border-indigo-500/20", type: 'comercial' },
      { id: '3', name: "Proposta Formalizada", color: "#8B5CF6", textClass: "text-[#8B5CF6]", bgClass: "bg-[#8B5CF6]/10", borderClass: "border-[#8B5CF6]/20", type: 'comercial' },
      { id: '4', name: "Análise de Crédito / Pasta", color: "#F59E0B", textClass: "text-amber-400", bgClass: "bg-amber-500/10", borderClass: "border-amber-500/20", type: 'comercial' },
      { id: '5', name: "Dono Recebeu / Chaves", color: "#10B981", textClass: "text-emerald-400", bgClass: "bg-emerald-500/10", borderClass: "border-emerald-500/20", type: 'comercial' },
    ],
  },
  {
    id: "automotivo_dealer",
    niche: "Automotivo",
    name: "Concessionária & Multimarcas",
    description: "Estoque de veículos, avaliação de usados, consignação, trocas e test-drives com funil de vendas e financiamento.",
    icon: Car,
    color: "#64748B",
    bgAccent: "bg-slate-500/10 border-slate-500/20 text-slate-300",
    modules: {
      crm: true,
      educacao: false,
      clinica: false,
      financeiro: true,
      marketing: true,
      engajamento: true,
      rh: true,
      bi: true,
    },
    stages: [
      { id: '1', name: "Lead / Interesse no Veículo", color: "#06B6D4", textClass: "text-[#06B6D4]", bgClass: "bg-[#06B6D4]/10", borderClass: "border-[#06B6D4]/20", type: 'comercial' },
      { id: '2', name: "Test-Drive Agendado", color: "#6366F1", textClass: "text-indigo-400", bgClass: "bg-indigo-500/10", borderClass: "border-indigo-500/20", type: 'comercial' },
      { id: '3', name: "Avaliação do Usado / Troca", color: "#8B5CF6", textClass: "text-[#8B5CF6]", bgClass: "bg-[#8B5CF6]/10", borderClass: "border-[#8B5CF6]/20", type: 'comercial' },
      { id: '4', name: "Proposta & Financiamento", color: "#F59E0B", textClass: "text-amber-400", bgClass: "bg-amber-500/10", borderClass: "border-amber-500/20", type: 'comercial' },
      { id: '5', name: "Veículo Entregue", color: "#10B981", textClass: "text-emerald-400", bgClass: "bg-emerald-500/10", borderClass: "border-emerald-500/20", type: 'comercial' },
    ],
  },
];
